  :Voom asciidoc
  This is VOoM markup mode test file. Converted from **test_outline.txt**.

findme findme2


h 1
===
   1 body
NEXT LINE IS FOR TESTS -- DO NOT MOVE OR EDIT
ID_LEVELS VO.levels=[1, 1, 2, 2, 1, 1, 2, 2, 3, 4, 3, 4, 5, 6, 7, 2, 1, 2, 1, 2, 2, 3, 3, 4, 5, 5, 3, 2, 3, 2, 3, 2, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 4, 2, 3, 4, 4, 5, 5, 5, 6, 4, 4, 3, 4, 4, 5, 5, 6, 5, 4, 4, 3, 4, 4, 4, 5, 6, 5, 5, 4, 3, 4, 4, 5, 6, 5, 5, 4, 4, 3, 4, 4, 4, 5, 5, 5, 6, 4, 3, 4, 4, 5, 5, 5, 6, 4, 4, 3, 3, 3, 2, 3, 3]


[[X2]]
h 1.1
-----
   1.1 body

[[X2]]
h 1.2
-----
   1.2 body


h 2
===
   2 body


h 3
===
   3 body

[[X2]]
h 3.1
-----
   3.1 body

[[X2]]
h 3.2
-----
   3.2 body

[[X3]]
[ATTR]
h 3.2.1
~~~~~~~
   3.2.1 body


h 3.2.1.1
^^^^^^^^^
   3.2.1.1 body
  xxxx findme findme

[[X3]]
[ATTR]
h 3.2.2
~~~~~~~
   3.2.2 body


h 3.2.2.1
^^^^^^^^^
   3.2.2.1 body


h 3.2.2.1.1
+++++++++++
   3.2.2.1.1 body


====== h 3.2.2.1.2.1 ======
   3.2.2.1.2.1 body


======= h 3.2.2.1.2.1.1 =======
   3.2.2.1.2.1.1 body

[[X2]]
h 3.3
-----
   3.3 body


h 4
===
   4 body

[[X2]]
h 4.1
-----
   4.1 body findme


h 5
===
   5 body

[[X2]]
h 5.1
-----
   5.1 body

[[X2]]
h 5.2
-----
   5.2 body

[[X3]]
[ATTR]
h 5.2.1
~~~~~~~
   5.2.1 body

[[X3]]
[ATTR]
h 5.2.2
~~~~~~~
   5.2.2 body


h 5.2.2.1
^^^^^^^^^
   5.2.2.1 body


h 5.2.2.1.1
+++++++++++
   5.2.2.1.1 body


h 5.2.2.1.2
+++++++++++
   5.2.2.1.2 body


[[X3]]
[ATTR]
h 5.2.3
~~~~~~~
   5.2.3 body

[[X2]]
h AA
----
a a a a

[[X3]]
[ATTR]
h AA.1
~~~~~~
a1 a1 a1 a1

[[X2]]
h BB
----
b b b b

[[X3]]
[ATTR]
h BB.1
~~~~~~
b1 b1 b1 b1 b1

[[X2]]
h 5.3
-----
   5.3 body
findme


h tests
=======

[[X2]]
h syntax tests
--------------
Since v2.1 comment chars before foldmarker are stripped according to filetype.
Some Body filetypes have their own Tree syntax hi.


[[X3]]
[ATTR]
h //---TODO comment--- //
~~~~~~~~~~~~~~~~~~~~~~~~~

[[X3]]
[ATTR]
h "---comment--- "
~~~~~~~~~~~~~~~~~~
echo 'vim ok'

[[X3]]
[ATTR]
h #---comment--- #
~~~~~~~~~~~~~~~~~~
print 'py ok'

[[X3]]
[ATTR]
h %---comment--- %
~~~~~~~~~~~~~~~~~~

[[X3]]
[ATTR]
h /*---comment--- /*
~~~~~~~~~~~~~~~~~~~~

[[X3]]
[ATTR]
h <!-- Comment
~~~~~~~~~~~~~~
ft=html,xml

[[X3]]
[ATTR]
h html head <!
~~~~~~~~~~~~~~

[[X3]]
[ATTR]
h /organizer node/
~~~~~~~~~~~~~~~~~~

[[X3]]
[ATTR]
h !warning mark
~~~~~~~~~~~~~~~

[[X2]]
h Voomgrep tests
----------------
:Voomg Spam and ham not bacon
:Voomg Spam and\ ham not\ bacon
:Voomg Spam and\\ ham not\\ bacon
\Spam// ' "

1 match
:Voomg Spam and ham and findme
:Voomg Spam and h\vam and \Vfin\.me


[[X3]]
[ATTR]
h n45 breakfast
~~~~~~~~~~~~~~~
eggs
bacon

[[X3]]
[ATTR]
h n46 lunch
~~~~~~~~~~~
Spam Spam Spam Spam Spam Spam Spam Spam Spam 
Spam Spam Spam Spam Spam Spam Spam Spam Spam 
Spam Spam Spam Spam Spam Spam Spam Spam Spam 
ham

[[X3]]
[ATTR]
h n47 dinner
~~~~~~~~~~~~
eggs
Spam
ham

[[X3]]
[ATTR]
h n48 snack
~~~~~~~~~~~
bacon
spam
HAM
beef


h empty
^^^^^^^

[[X2]]
h VoomSort tests
----------------

[[X3]]
[ATTR]
h {VoomSort}
~~~~~~~~~~~~


h ЭЭЭ
^^^^^
Э


h ЯЯЯ
^^^^^
Я


h bbb
+++++
b


h BBB
+++++
B


h aaa
+++++
a


====== h 111 ======
1


h эээ
^^^^^
э


h яяя
^^^^^
я

[[X3]]
[ATTR]
h {VoomSort deep}
~~~~~~~~~~~~~~~~~


h ЭЭЭ
^^^^^
Э


h ЯЯЯ
^^^^^
Я


h BBB
+++++
B


h aaa
+++++
a


====== h 111 ======
1


h bbb
+++++
b


h эээ
^^^^^
э


h яяя
^^^^^
я

[[X3]]
[ATTR]
h {VoomSort deep i}
~~~~~~~~~~~~~~~~~~~


h ЭЭЭ
^^^^^
Э


h эээ
^^^^^
э


h ЯЯЯ
^^^^^
Я


h aaa
+++++
a


====== h 111 ======
1


h bbb
+++++
b


h BBB
+++++
B


h яяя
^^^^^
я

[[X3]]
[ATTR]
h {VoomSort deep i bytes}
~~~~~~~~~~~~~~~~~~~~~~~~~


h ЭЭЭ
^^^^^
Э


h ЯЯЯ
^^^^^
Я


h aaa
+++++
a


====== h 111 ======
1


h bbb
+++++
b


h BBB
+++++
B


h эээ
^^^^^
э


h яяя
^^^^^
я

[[X3]]
[ATTR]
h {VoomSort deep i bytes r}
~~~~~~~~~~~~~~~~~~~~~~~~~~~


h яяя
^^^^^
я


h эээ
^^^^^
э


h ЯЯЯ
^^^^^
Я


h BBB
+++++
B


h bbb
+++++
b


h aaa
+++++
a


====== h 111 ======
1


h ЭЭЭ
^^^^^
Э

[[X3]]
[ATTR]
h {VoomSort deep i r}
~~~~~~~~~~~~~~~~~~~~~


h яяя
^^^^^
я


h ЯЯЯ
^^^^^
Я


h bbb
+++++
b


h BBB
+++++
B


h aaa
+++++
a


====== h 111 ======
1


h эээ
^^^^^
э


h ЭЭЭ
^^^^^
Э

[[X3]]
[ATTR]
h ñññ
~~~~~

[[X3]]
[ATTR]
h ÑÑÑ
~~~~~

[[X3]]
[ATTR]
h zzz
~~~~~

[[X2]]
h special chars tests
---------------------

[[X3]]
[ATTR]
h '" /\\/
~~~~~~~~~
" "" """
' '' """
\ \\ \\\
/ // ///
\//\

[[X3]]
[ATTR]
h Брожу ли я
~~~~~~~~~~~~
    Брожу. Чего ж не побродить.

Чебурашка CHeburashka
u'\u0427\u0435\u0431\u0443\u0440\u0430\u0448\u043a\u0430'
utf-8
'\xd0\xa7\xd0\xb5\xd0\xb1\xd1\x83\xd1\x80\xd0\xb0\xd1\x88\xd0\xba\xd0\xb0'

Strikethrough: U+0336 (COMBINING LONG STROKE OVERLAY)
Э̶Ю̶Я̶ A̶̶B̶̶C̶̶

IMPORTANT: The last line must be blank (include spaces and tabs to make it more interesting). Otherwise :VoomSort tests fail for rest, asciidoc, etc.
 	 	
